### PR TITLE
New Logo and Wireflow

### PR DESCRIPTION
**Pull request by srlhyo**
Ma man Nuno 👷‍♂️

I worked a bit more on the app design, including the Logo looks. Also, main changes happened in the README file:
- Changed and aligned the logo to center  _I think it looks way better!_ 
- The document title was moved after the logo, as it makes more sense. 
- Wireflow was replaced for the new. You can go to figma from [here](https://www.figma.com/file/YgAM4iYSwMSTgj6FjShzAq/WIREFLOW-ISAT?node-id=0%3A1) should you want to see it better. 

Some images to back up:

__New Logo!!!__

__Mobile Version__

__New WIREFLOW__

### CODE REVIEW

**Comment by GRC-Cyber** [comment]
Great to see that you took my comments on board about the design of the logo. I agree, the logo looks way better! One small detail that perhaps should be considered is the order of the colours. I think that it should go from green, which is the optimal status, then amber and finally red, which is the lesser of them all. What do you think?

The new Wireflow plays only the first two slides o Figma. Did you intend to play/show only the first two slides?

**Comment by srlhyo** [comment]
Humm, intuitively when I look the logo I think of the traffic lights, which makes think for a moment before making any decision. But your idea isn't bad too. If you prefer the colors to change orders, that can quickly be done though. 

The fig prototype is fixed now 😄

**Comment by GRC-Cyber** [comment]
Lets have for now the colours going from green to red, and we'll revisit it as we develop the prototype.

I am going to write a short text now for the slide 2 'Why Testing?'. Please bear with me.

**Comment by GRC-Cyber** [comment]
What do you think of brief test:

The ubiquity and regularity of data breaches is a bad omen that maintaining the confidentiality, integrity and availability (CIA triad) of information remains a big challenge for businesses across the world. During the year 2019, many businesses were affected. It continues to be today's reality. Rather than firefighting, ISAT puts your business one step ahead.

**Comment by GRC-Cyber** [comment]
The ubiquity and regularity of data breaches is a bad omen that maintaining the confidentiality, integrity and availability (CIA triad) of information remains a big challenge for businesses across the world. During the year 2019, many businesses were affected by data breaches and cyber attacks. It continues to be today's reality. Rather than firefighting, ISAT puts your business one step ahead, helping you maintain the trust of your clients and stakeholders.

**Comment by srlhyo** [comment]
cool. I am going to make all the changes now. You can close this pull request. A new one will be made.

**Pull request closed without merging**
