### PR TITLE
Readme file and and wireflow updated

### PR DESCRIPTION
**Pull request by srlhyo**
Ma man Nuno 👷‍♂️ 

Readme file (logo included) and Wireflow (can be seen in Figma)  updated as suggested in the last pull request.

### CODE REVIEW

**Comment by GRC-Cyber** [comment]
You forgot to include the logo changes on the Readme file. I only see the changes for the Wireflow.

**Comment by srlhyo** [comment]
It has already been included.  Here's a screenshot:

**Comment by GRC-Cyber** [comment]
I changed the logo position to left rather than centre. It looks better that way. I have also deleted the Information Security Assessment Tool given that it's already included in the logo and it avoids duplication.

**Comment by srlhyo** [comment]
Nice! 👍

**Pull request merged**
